Added a OHLC candlestick graph
opencode18/dataviz-gallery pull request #6
Opened 2018-01-19 19:21 UTC by Jigar3

2018-01-19 19:24 UTC, mubaris requested changes
Add the link to the viz in README

2018-01-19 19:24 UTC, mubaris commented on Equity-graphs/plot.py
> +mpl.style.use('default')
Use `ggplot` style

2018-01-19 21:13 UTC, gauthamzz commented
@Jigar3 you need to edit the readme and link the visualisation you made.

2018-01-20 05:58 UTC, mubaris approved these changes

2018-01-20 05:58 UTC, merged